### ISSUE TITLE
Better CSS examples

### ISSUE THREAD

**Issue by chauff** [chauff/Web-Teaching#102]
At the moment, every example introduces something different in the CSS lecture. A single unifying project that is expanded throughout the lecture would be better.

**Comment by radoslav55** [comment]
@chauff Should we consider replacing all of the examples in the lecture with the project? Since there are some code examples which act more as a playground (e.g the examples with `float`, `Selector combinations`), and probably would be easier for the students if those examples are as small as possible, so that they can understand the topics better.
In addition, my idea for this task is to have an initial template in the first code snippet, and from then on every next example will give the new code that should be placed in the template, and at the end of the lecture we can have a snippet with the entire code in one place.
Please, tell me if i'm in the right track.
