### ISSUE TITLE
Sourcemaps

### ISSUE THREAD

**Issue by chauff** [chauff/Web-Teaching#106]
Introduce sourcemaps?

**Comment by radostefanov** [comment]
Sourcemaps are indeed a great tool, but since the concept of minification, or tools like webpack and languages that compile to JavaScript (like TypeScript) are not discussed in details in the scope of the course, i think that sourcemaps would be rather unnecessary, and students will probably find it hard to understand without knowing about the above mentioned tools. Maybe we can include a link somewhere in Lecture 3 for students who want to know something additional.

**Comment by chauff** [comment]
Good point. Closing for now.
