### ISSUE TITLE
Web design update

### ISSUE THREAD

**Issue by chauff** [chauff/Web-Teaching#127]
http://atomicdesign.bradfrost.com/chapter-1/

**Comment by chauff** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/designMode (mention at least? or showcase in a demo)

**Comment by lyrakisk** [comment]
The broadfrost article is very nice, should I put it as a link in lecture's 2 recommended readings?
One thing to consider: the current first-year students were born in 2001 so probably they don't see the web as a collection of "pages". They grew up seeing everything as an "app" with the introduction of smartphones in 2007. So maybe the article is not so relevant to them. 

Regarding the document.designMode I would suggest to showcase it in class but I wouldn't add it in the lecture notes since most students won't probably use it.

@chauff @azqa

**Comment by azqa** [comment]
> One thing to consider: the current first-year students were born in 2001 so probably they don't see the web as a collection of "pages". They grew up seeing everything as an "app" with the introduction of smartphones in 2007. So maybe the article is not so relevant to them.

I would argue that it is crucial to understand where the web started from, in order to understand it's issues, or design principles for example. We still see collection of web pages today (e.g. academic personal websites).
